const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 1200,
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      numReviews: 20,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 1300,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Lee Free Shirt',
      category: 'Shirts',
      image: '/images/d1.jpg',
      price: 1820,
      countInStock: 10,
      brand: 'Lee',
      rating: 4,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/d2.jpg',
      price: 999,
      countInStock: 15,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/d3.jpg',
      price: 1500,
      countInStock: 5,
      brand: 'Puma',
      rating: 5,
      numReviews: 30,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/shirt1.jpg',
      price: 950,
      countInStock: 12,
      brand: 'Adidas',
      rating: 3.5,
      numReviews: 25,
      description: 'high quality product',
    },
    {
      _id: '7',
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/shirt1.jpg',
      price: 950,
      countInStock: 12,
      brand: 'Adidas',
      rating: 3.5,
      numReviews: 25,
      description: 'high quality product',
    },
    {
      _id: '8',
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/shirt1.jpg',
      price: 950,
      countInStock: 12,
      brand: 'Adidas',
      rating: 3.5,
      numReviews: 25,
      description: 'high quality product',
    },
  ],
};
export default data;